### ISSUE TITLE
Parameter app not found, when upgrading

### ISSUE THREAD

**Issue by andremohrmann** [Scribblerockerz/cryptletter#4]
```
if (configuration.app.assets) {
                     ^

TypeError: Cannot read property 'assets' of undefined
    at Object.<anonymous> (/snapshot/cryptletter/index.js:77:22)
    at Module._compile (pkg/prelude/bootstrap.js:1226:22)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1281:12)
    at startup (bootstrap_node.js:200:16)
    at bootstrap_node.js:617:3
```

**Comment by Scribblerockerz** [comment]
Fixed with release v1.1.0
