### ISSUE TITLE
[SOLVED] Adding files causes crash: JSON decoder out of sync

### ISSUE THREAD

**Issue by jphovila** [Scribblerockerz/cryptletter#48]
Hi!

I'm running Cryptletter version 3.1.2 inside a FreeBSD 13.2 jail.

Creating plain text messages works fine, but trying to add file attachments almost always results in:

```
http: panic serving xxx.xxx.xxx.xxx:yyyyy: JSON decoder out of sync - data changing underfoot?
goroutine 37 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go120/src/net/http/server.go:1854 +0xbf
panic({0x9adb60, 0xf13d30})
        /usr/local/go120/src/runtime/panic.go:890 +0x263
encoding/json.(*decodeState).literalStore(0xc00013c3e8, {0xc000c0000b, 0x42, 0x7ffdf5}, {0x9adb60?, 0xc000126248?, 0x1?}, 0x0)
        /usr/local/go120/src/encoding/json/decode.go:946 +0x22f1
encoding/json.(*decodeState).value(0xc00013c3e8, {0x9adb60?, 0xc000126248?, 0xc000c00002?})
        /usr/local/go120/src/encoding/json/decode.go:388 +0x126
encoding/json.(*decodeState).object(0xc00013c3e8, {0x9986e0?, 0xc000126240?, 0xc0002575a8?})
        /usr/local/go120/src/encoding/json/decode.go:775 +0xd45
encoding/json.(*decodeState).value(0xc00013c3e8, {0x9986e0?, 0xc000126240?, 0xc0002575f8?})
        /usr/local/go120/src/encoding/json/decode.go:374 +0x45
encoding/json.(*decodeState).unmarshal(0xc00013c3e8, {0x9986e0?, 0xc000126240?})
        /usr/local/go120/src/encoding/json/decode.go:181 +0x168
encoding/json.(*Decoder).Decode(0xc00013c3c0, {0x9986e0, 0xc000126240})
        /usr/local/go120/src/encoding/json/stream.go:73 +0x191
github.com/Scribblerockerz/cryptletter/pkg/handler.NewMessageAction({0xf1b290, 0xc00014c2a0}, 0xc000136e00)
        /home/privnoted/Cryptletter/cryptletter/pkg/handler/handlers.go:241 +0xf0
net/http.HandlerFunc.ServeHTTP(0x100?, {0xf1b290?, 0xc00014c2a0?}, 0x40dce7?)
        /usr/local/go120/src/net/http/server.go:2122 +0x2f
github.com/Scribblerockerz/cryptletter/pkg/logger.HTTPLogger.func1({0xf1b290, 0xc00014c2a0}, 0xc000136e00)
        /home/privnoted/Cryptletter/cryptletter/pkg/logger/logger.go:17 +0x9e
net/http.HandlerFunc.ServeHTTP(0xc000136d00?, {0xf1b290?, 0xc00014c2a0?}, 0xc0001309e8?)
        /usr/local/go120/src/net/http/server.go:2122 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000000180, {0xf1b290, 0xc00014c2a0}, 0xc000136c00)
        /home/privnoted/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
net/http.serverHandler.ServeHTTP({0xf19918?}, {0xf1b290, 0xc00014c2a0}, 0xc000136c00)
        /usr/local/go120/src/net/http/server.go:2936 +0x316
net/http.(*conn).serve(0xc00013a5a0, {0xf1b8d0, 0xc0001e8f60})
        /usr/local/go120/src/net/http/server.go:1995 +0x612
created by net/http.(*Server).Serve
        /usr/local/go120/src/net/http/server.go:3089 +0x5ed
```

With really tiny files, the crash does not always happen. But trying to attach a file of just 1 MB in size will definitely result in the above error.

Resource limits for the user account under which my Cryptletter daemon is running are:

```
Resource limits (current):
  cputime              infinity secs
  filesize             infinity kB
  datasize             33554432 kB
  stacksize              524288 kB
  coredumpsize         infinity kB
  memoryuse            infinity kB
  memorylocked           131072 kB
  maxprocesses            89999
  openfiles             3771063
  sbsize               infinity bytes
  vmemoryuse           infinity kB
  pseudo-terminals     infinity
  swapuse              infinity kB
  kqueues              infinity
  umtxp                infinity
```
Googling with the error message gave a bunch of results which may give some hints of where things go wrong, but nothing that would help me (as a server architect, not that much of a programmer) to fix the issue.

**Comment by Scribblerockerz** [comment]
Hey @jphovila, thanks for letting me know.

It looks like this race condition might be FreeBSD jail specific, at least I couldn't reproduce the error on mac nor PopOS! 22.04.

Still, the issue seems to be solved (at least for other repositories) by copying the memory from the request to an other buffer before decoding it.

https://github.com/Scribblerockerz/cryptletter/releases/tag/3.1.4

Let me know if the fix worked out!

**Comment by Scribblerockerz** [comment]
I've setup an nginx as a reverse proxy (inside docker) but unfortunately, I couldn't reproduce the issue.

With the 3.1.5 release, I'm trimming any '\x00' bytes from the buffer.

https://github.com/Scribblerockerz/cryptletter/releases/tag/3.1.5

It would be great if you could check the the latest version.

**Comment by Scribblerockerz** [comment]
Hey @jphovila, I forgot that it's possible to declare FreeBSD as compilation target. Personally I never used it, so it did not come into my mind earlier.

I've build the 3.1.5 again for FreeBSD and attached the binary to the release.

If it's still failing, I might have to dig deeper into FreeBSD jails, so a hint on how to set it up would be great.

**Comment by Scribblerockerz** [comment]
This is great news! I was glad to help.
